import React from 'react';
import Head from 'next/head';
import Link from 'next/link';


const Layout = ({children,title}) => {
    return (
        <>
            <Head>
                <title>{title? title + ' - Amazon': 'Amazon'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex min-h-screen flex-col justify-between '>
                <header>
                    <nav className='flex h-12 justify-between shadow-md items-center px-5'>
                        <Link href={'/'}>
                            <a className='text-lg font-bold font-manrope '>Amazon</a>
                        </Link>
                        <div>
                            <Link href={'/cart'}><a className='p-2'>Cart</a></Link>
                            <Link href={'/login'}><a className='p-2'>Login</a></Link>
                        </div>
                    </nav>
                </header>
                <main className='container m-auto mt-4 px-4'>
                    {children}
                </main>
                <footer className='flex justify-center items-center shadow-inner h-10'>
                    Copyright 2022 Amazon   
                </footer>
            </div>
        </>
    );
};

export default Layout;