import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

const RentyaHomeScreen = ({children,title}) => {
    return (
        <>
            <Head>
                <title>{title? title + ' - Amazon': 'Amazon'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex min-h-screen flex-col'>
                <div className='flex min-w-screen h-96 flex-col border-2 bg-rentya_home_bg bg-cover px-10 py-8'>
                    <nav className='flex justify-between'>
                        <div className='font-manrope font-bold text-white text-xl'>rentya</div>
                        <div className=''></div>
                    </nav>
                </div>
            </div>
        </>
    );
};

export default RentyaHomeScreen;